


name: test

on:
  push:
      branches:
        - dev
      paths: 
        - "github/workflows/**"
        - "test/**"
        - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 14
        uses: actions/setup-node@v3
        with:
            node-version: 14
      - name: lint and test
        run: |
          npm install
          npm run lint
          npm test
